---
- name: Workstation Setup
  hosts: localhost
  become: true

  vars_files:
    - vars/vars.yml

  tasks:
    - include_tasks: tasks/setup.yml
    - include_tasks: tasks/repos.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/thirdparty.yml
