---
- name: Workstation Setup
  hosts: localhost
  become: true

  vars_files:
    - vars/vars.yml

  tasks:
    - include_tasks: tasks/setup-{{ ansible_pkg_mgr }}.yml
    - include_tasks: tasks/setup-{{ ansible_pkg_mgr }}.yml
    - include_tasks: tasks/dotfiles.yml
