[hostname]
ssh_only = false
prefix = "⟪"
suffix = "⟫"
trim_at = "."
disabled = false


[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"
